<?php global $base_url;
$theme_path = $base_url.'/'.path_to_theme(); ?>

<footer>

    <ul class="footer_left_menu">

      <li><a href="<?php echo $base_url;?>/sitemap">Sitemap</a></li>
      <li><a href="<?php echo $base_url;?>/terms">Terms & Conditions </a></li>
      <li><a href="<?php echo $base_url;?>/privacy-policy">Privacy Policy</a></li>
    </ul>
    <div class="right_box">
      <div class="logo1"><img src="<?php echo $theme_path; ?>/images/greemlen.png" alt=""></div>
      <div class="socails">
        <ul>
          <li><a href="#"><img class="main" src="<?php echo $theme_path; ?>/images/face1.png" alt=""> <img src="<?php echo $theme_path; ?>/images/face1_hover.png" class="overlay1" alt=""></a></li>
          <li><a href="#"><img class="main" src="<?php echo $theme_path; ?>/images/twitter1.png" alt=""> <img src="<?php echo $theme_path; ?>/images/twitter1_hover.png" class="overlay1" alt=""></a></li>
          <li><a href="#"><img class="main" src="<?php echo $theme_path; ?>/images/google1.png" alt=""> <img src="<?php echo $theme_path; ?>/images/google1_hover.png" class="overlay1" alt=""></a></li>
          <li><a href="#"><img class="main" src="<?php echo $theme_path; ?>/images/pinast1.png" alt=""> <img src="<?php echo $theme_path; ?>/images/pinast1_hover.png" class="overlay1" alt=""></a></li>
        </ul>
      </div>
      <div class="copy">Copyright © 2015 </div>
    </div>
</footer>
  

  <script type="text/javascript" src="<?php echo $theme_path;?>/js/jquery-1.7.2.min.js"></script> 
<!--<script type="text/javascript" src="<?php echo $theme_path;?>/js/PIE.js"></script> -->
<script type="text/javascript" src="<?php echo $theme_path;?>/js/jquery.mCustomScrollbar.concat.min.js"></script> 
<script type="text/javascript" src="<?php echo $theme_path;?>/js/slidebars.js"></script> 

<script type="text/javascript" src="<?php echo $theme_path;?>/js/html5.js"></script> 
<script type="text/javascript" src="<?php echo $theme_path;?>/js/jquery.fullPage.js"></script> 


<script src="<?php echo $theme_path;?>/js/script.js"></script>
<script src="<?php echo $theme_path;?>/js/html5.js"></script>

<!-- start bxslider --> 
<script  src="<?php echo $theme_path;?>/js/jquery.bxslider.js"></script>

<!-- end bxslider -->
