<?php 
global $base_url;
$theme_path = $base_url.'/'.path_to_theme();
?>

<link rel="stylesheet" type="text/css" href="<?php echo $theme_path;?>/css/animate3.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $theme_path;?>/css/buttons.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $theme_path;?>/css/keyframes.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $theme_path;?>/css/jquery.fullPage.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $theme_path;?>/css/jquery.mCustomScrollbar.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $theme_path;?>/css/menu_icon.css" />
<link rel="stylesheet"  href="<?php echo $theme_path;?>/css/layout.css" />
<link rel="stylesheet"  href="<?php echo $theme_path;?>/css/screen.css" />
<link rel="stylesheet"  href="<?php echo $theme_path;?>/css/slidebars.css" />
<link rel="stylesheet"  href="<?php echo $theme_path;?>/css/jquery.bxslider.css" />
