<?php
/**
 * Implementation of hook_form_alter().
 *
 * The function is named custom_form_alter.
 */
function custom_form_alter(&$form, $form_state, $form_id) {
    
    // Normally a switch is used because you may want to alter more than
    // one form and it is easy to add a new case for each form.
    switch ($form_id) {
        // This is our form ID.
        case 'webform-client-form-145':
            // Our kickin' mods go here.
            $form['actions']['submit']['#attributes'] = array('class' => 'my_class');

            break;
    }
}


?>